#pragma once

__BEGIN_DECLS

typedef enum {
  SQC_RPC_SCHED_USER_ROLE_TYPE_UNKNOWN = 0,
  SQC_RPC_SCHED_USER_ROLE_TYPE_GENERAL = 1,
  SQC_RPC_SCHED_USER_ROLE_TYPE_ADMIN = 2,
} sqc_rpc_sched_user_role_type_t;

typedef enum {
  SQC_RPC_SCHED_USER_STATUS_UNKNOWN = 0,
  SQC_RPC_SCHED_USER_STATUS_DISABLED = 1,
  SQC_RPC_SCHED_USER_STATUS_ENABLED = 2,
} sqc_rpc_sched_user_status_t;

typedef enum {
  SQC_RPC_SCHED_CIRCUIT_FMT_UNKNOWN = 0,
  SQC_RPC_SCHED_CIRCUIT_FMT_QASM = 1,
  SQC_RPC_SCHED_CIRCUIT_FMT_QIR = 2,
  SQC_RPC_SCHED_CIRCUIT_FMT_QPY = 3,
  SQC_RPC_SCHED_CIRCUIT_FMT_JSON = 4,
  SQC_RPC_SCHED_CIRCUIT_FMT_JSON_NUM = 5,
} sqc_rpc_sched_circuit_fmt_t;

typedef enum {
  SQC_RPC_SCHED_QC_TYPE_UNKNOWN = 0,
  SQC_RPC_SCHED_QC_TYPE_RQC_REST = 1,
  SQC_RPC_SCHED_QC_TYPE_IBM_REST = 2,
  SQC_RPC_SCHED_QC_TYPE_SLURM_REST = 3,
  SQC_RPC_SCHED_QC_TYPE_QTM_GRPC = 4,
  SQC_RPC_SCHED_QC_TYPE_QTM_SIM_GRPC = 5,
  SQC_RPC_SCHED_QC_TYPE_IBM_DACC = 6,
  SQC_RPC_SCHED_QC_TYPE_A_OQTOPUSREST_SYSTEM_TOKEN = 7,
  SQC_RPC_SCHED_QC_TYPE_A_OQTOPUSREST_USER_TOKEN = 8,
  SQC_RPC_SCHED_QC_TYPE_A_OQTOPUSREST_BOTH_TOKEN = 9,
  SQC_RPC_SCHED_QC_TYPE_NUM = 10,
  SQC_RPC_SCHED_QC_TYPE_DUMMY = 99999,
} sqc_rpc_sched_qc_type_t;

typedef enum {
  SQC_RPC_SCHED_TRANSPILER_UNKNOWN = 0,
  SQC_RPC_SCHED_TRANSPILER_NONE = 1,
  SQC_RPC_SCHED_TRANSPILER_PASS = 2,
  SQC_RPC_SCHED_TRANSPILER_NORMAL = 3,
  SQC_RPC_SCHED_TRANSPILER_NUM = 4,
} sqc_rpc_sched_transpiler_t;

typedef enum {
  SQC_RPC_SCHED_JOB_STATUS_UNKNOWN = 0,
  SQC_RPC_SCHED_JOB_STATUS_CREATED = 1,
  SQC_RPC_SCHED_JOB_STATUS_QUEUED = 2,
  SQC_RPC_SCHED_JOB_STATUS_RUNNING = 3,
  SQC_RPC_SCHED_JOB_STATUS_DONE = 4,
  SQC_RPC_SCHED_JOB_STATUS_CANCELLED = 5,
  SQC_RPC_SCHED_JOB_STATUS_ERROR = 6,
  SQC_RPC_SCHED_JOB_STATUS_DELETED = 7,
} sqc_rpc_sched_job_status_t;

__END_DECLS

