#pragma once

#include "sqc_rpc_sched_paths.h"

__BEGIN_DECLS

#define SQC_RPC_SCHED_MAX_PRIORITY 9

// Weights based on priority
#define SQC_RPC_SCHED_WEIGHT_SCALE 1000

// Hours-to-milliseconds conversion factor
#define SQC_RPC_SCHED_EXEC_TIME_LIMIT_HOUR_SCALE 3600000ull

#define SQC_RPC_SCHED_DEFAULT_GROUP_ID "default"

#define SQC_RPC_SCHED_USER_GROUP_KEY_SEP ":"
#define SQC_RPC_SCHED_USER_GROUP_KEY_SEP_LEN (sizeof(SQC_RPC_SCHED_USER_GROUP_KEY_SEP) - 1)

#define SQC_RPC_SCHED_USER_ID_MAX_SIZE 256
#define SQC_RPC_SCHED_GROUP_ID_MAX_SIZE 256

#define SQC_RPC_SCHED_USER_GROUP_KEY_MAX_SIZE ((SQC_RPC_SCHED_USER_ID_MAX_SIZE) + \
                                               (SQC_RPC_SCHED_USER_GROUP_KEY_SEP_LEN) + \
                                               (SQC_RPC_SCHED_GROUP_ID_MAX_SIZE))
#define SQC_RPC_SCHED_JOB_ID_MAX_SIZE 36 // UUID
#define SQC_RPC_SCHED_QC_JOB_ID_MAX_SIZE 256
#define SQC_RPC_SCHED_QPROGRAM_MAX_SIZE 64 * 1024
#define SQC_RPC_SCHED_REMARK_MAX_SIZE 1024
#define SQC_RPC_SCHED_RESULT_MAX_SIZE 64 * 1024
#define SQC_RPC_SCHED_USER_TOKEN_MAX_SIZE 1024

/* Request Invoker(Priority Queue) */
#define SQC_RPC_SCHED_PQ_NUM (SQC_RPC_SCHED_MAX_PRIORITY + 1)
#define SQC_RPC_SCHED_PQ_LEN 100LL
#define SQC_RPC_SCHED_PQ_PUT_TIMEOUT (100LL * 1000LL * 1000LL)
#define SQC_RPC_SCHED_PQ_GET_TIMEOUT (10LL * 1000LL * 1000LL)

/* DB */
#define SQC_RPC_SCHED_DB_FILE APP_VARDIR "/sqc-scheduler.db"
#define SQC_RPC_SCHED_DB_TIMEOUT 3000

/* Server Session */
#define SQC_RPC_SCHED_SRV_ADDR_PORT "127.0.0.1:30001"
#define SQC_RPC_SCHED_SRV_MAX_SESSION 4096
#define SQC_RPC_SCHED_SRV_THD_INTERVAL (1000LL * 1000LL * 1000LL)

__END_DECLS

